"""Campus Navigator Flask server.

Maintenance note:
- Edit campus places in data/locations.json, then open /sync to update SQLite.
- Frontend pages are in templates/; browser behavior is in static/js/.
"""

from flask import Flask, render_template, request, jsonify, abort
import sqlite3
import json
import re

app = Flask(__name__)

# Panorama scenes are intentionally allowlisted so only published campus
# scenes can be opened by URL. Add the next real photosphere here when it is
# captured and connected to an indoor hotspot.
PANORAMA_SCENES = {
    "lt-202": {
        "id": "lt-202",
        "title": "LT-202",
        "building": "Tech Block",
        "floor": "2nd Floor",
        "image": "/static/panoramas/lt-202.jpg",
        "haov": 360,
        "vaov": 120,
        "v_offset": 0,
    }
}


def panorama_for_location(name):
    """Return a published panorama URL for a location, if one exists."""
    scene = next(
        (scene for scene in PANORAMA_SCENES.values()
         if scene["title"].lower() == (name or "").lower()),
        None,
    )
    return f"/panorama/{scene['id']}" if scene else ""


def normalize_search(value):
    """Make searches tolerant of spaces, hyphens, underscores, and casing."""
    return re.sub(r"[^a-z0-9]", "", (value or "").casefold())


def location_matches(location, query):
    """Return a relevance score for flexible name/building/keyword matching."""
    needle = normalize_search(query)
    if not needle:
        return 0

    name = normalize_search(location["name"])
    building = normalize_search(location["building"])
    floor = normalize_search(location["floor"])
    keywords = normalize_search(location["keywords"])

    if needle == name:
        return 0
    if name.startswith(needle):
        return 1
    if needle in name:
        return 2
    if needle in building:
        return 3
    if needle in floor:
        return 4
    if needle in keywords:
        return 5
    return None


def find_locations(query, limit=None):
    """Search all campus records using the same flexible matching everywhere."""
    conn = get_db_connection()
    rows = conn.execute("""
        SELECT name, building, floor, lat, lng,
               image, instructions, entry_lat, entry_lng, keywords
        FROM locations
    """).fetchall()
    conn.close()

    ranked = []
    for row in rows:
        location = dict(row)
        score = location_matches(location, query)
        if score is not None:
            ranked.append((score, location["name"].casefold(), location))
    ranked.sort(key=lambda item: (item[0], item[1]))
    locations = [item[2] for item in ranked]
    return locations[:limit] if limit else locations


# Allow iframe embedding and disable cache for Replit preview
@app.after_request
def set_headers(response):
    response.headers["X-Frame-Options"] = "ALLOWALL"
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
    return response


# ---------------- DATABASE CONNECTION ----------------
def get_db_connection():
    # Keeping the row factory lets routes convert database rows to JSON/dicts.
    conn = sqlite3.connect("campus.db")
    conn.row_factory = sqlite3.Row
    return conn


# ---------------- HOME ----------------
@app.route("/")
def home():
    return render_template("home.html")


# ---------------- DIRECTIONS PAGE ----------------
@app.route("/directions")
def directions():
    query = request.args.get("q", "").strip()

    if not query:
        return render_template("results.html", location=None, query=query)

    locations = find_locations(query, limit=1)
    location = locations[0] if locations else None
    if location:
        location["panorama_url"] = panorama_for_location(location["name"])
    return render_template("results.html", location=location, query=query)


# ---------------- MAP PAGE ----------------
@app.route("/map")
def map_page():
    # Support both links generated by the app and manual URLs such as /map?q=Library.
    destination = request.args.get("destination") or request.args.get("q", "")
    return render_template("map.html", destination=destination)


# ---------------- SEARCH (JSON) ----------------
@app.route("/search")
def search_location():
    query = request.args.get("q", "").strip()

    locations = find_locations(query, limit=1)
    if locations:
        location = locations[0]
        location.pop("keywords", None)
        location["panorama_url"] = panorama_for_location(location["name"])
        return jsonify(location)
    return jsonify({})


# ---------------- 360° INDOOR VIEWER ----------------
@app.route("/panorama/<scene_id>")
def panorama(scene_id):
    scene = PANORAMA_SCENES.get(scene_id)
    if not scene:
        abort(404)
    return render_template("panorama.html", scene=scene)


# ---------------- SUGGEST ----------------
@app.route("/suggest")
def suggest():
    query = request.args.get("q", "").strip()
    return jsonify([location["name"] for location in find_locations(query, limit=8)])


# ---------------- SYNC JSON → DB ----------------
def sync_json_to_db():
    conn = sqlite3.connect("campus.db")
    cursor = conn.cursor()

    with open("data/locations.json", "r") as file:
        data = json.load(file)

    for loc in data:
        cursor.execute("""
        INSERT OR REPLACE INTO locations
        (name, building, floor, lat, lng, type, image, instructions, entry_lat, entry_lng, keywords)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            loc.get("name"),
            loc.get("building"),
            loc.get("floor"),
            loc.get("lat"),
            loc.get("lng"),
            loc.get("type", "general"),
            loc.get("image", ""),
            loc.get("instructions", ""),
            loc.get("entry_lat", loc.get("lat")),
            loc.get("entry_lng", loc.get("lng")),
            loc.get("keywords", ""),
        ))

    conn.commit()
    conn.close()
    print("JSON synced to DB")


# ---------------- NEARBY PAGE ----------------
@app.route("/nearby")
def nearby():
    return render_template("nearby.html")


# ---------------- ALL LOCATIONS API ----------------
@app.route("/api/locations")
def all_locations():
    conn = get_db_connection()
    rows = conn.execute(
        "SELECT name, building, floor, lat, lng, type, instructions FROM locations"
    ).fetchall()
    conn.close()
    return jsonify([dict(r) for r in rows])


# ---------------- SYNC ROUTE ----------------
@app.route("/sync")
def sync():
    sync_json_to_db()
    return "Data synchronized successfully!"


# ---------------- RUN ----------------
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False, use_reloader=False)
